version: "3.9"

services:
  bot:
    image: tiebameow/tiebamanagebot:latest
    container_name: tiebamanagebot_app
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./bot_data:/app/data
      - ./bot_logs:/app/logs
    ports:
      - "18765:18765"
    restart: unless-stopped
